const DEFAULT_NAME = "Tài khoản";
const UPPER_MALE_LABEL = "Anh";
const UPPER_FEMALE_LABEL = "Chị";
const LOWER_FEMALE_LABEL = "chị";
const LOWER_MALE_LABEL = "anh";
const CUSTOMER_UNKNOWN_NAME = "Không xác định";
const FEMALE_TEXT = "Nữ";
const MALE_TEXT = "Nam";

module.exports = {
  DEFAULT_NAME,
  UPPER_MALE_LABEL,
  UPPER_FEMALE_LABEL,
  LOWER_FEMALE_LABEL,
  LOWER_MALE_LABEL,
  CUSTOMER_UNKNOWN_NAME,
  FEMALE_TEXT,
  MALE_TEXT,

};
