const REDIS_KEY_PREFIX = "SAMPLE_APP:";
const APP_CONFIG_REDIS_KEY = `${REDIS_KEY_PREFIX}APP_CONFIG`;
const OTP_REDIS_KEY = `${REDIS_KEY_PREFIX}OTP:`;

module.exports = {
  OTP_REDIS_KEY,
  APP_CONFIG_REDIS_KEY,
};
